src/api/words/post-word.api.ts
src/atoms/StyledCloudRefresher.tsx
src/atoms/StyledFadingIcon.tsx
src/atoms/StyledIconButtonX.tsx
src/components/molecule_appbar_search_bar/index.tsx
src/hooks/words/use-post-word.hook.ts

DOC PR: https://github.com/ajktown/docs/pull/3
FE PR: https://github.com/ajktown/wordnote/pull/20
API PR: https://github.com/ajktown/api/pull/3

Local connection test between Local Mongo DB, API and FE

---

src/api/words/interfaces/index.search-params.ts
src/components/molecule_appbar_search_bar/index.tsx
src/components/molecule_new_word_box/index.tsx
src/components/organism_word_card_chunk/index.search_found.tsx
src/components/organism_word_card_chunk/index.search_not_found.tsx
src/hooks/words/use-reset-search-input.hook.ts
src/hooks/words/use-word-ids.hook.ts
src/recoil/index.keys.ts
src/recoil/words/searchInput.state.ts

API: https://github.com/ajktown/api/pull/7
FE: https://github.com/ajktown/wordnote/pull/25

Get words with search input

---

src/api/index.interface.ts
src/api/semesters/get-semester-by-code.api.ts
src/api/semesters/get-semesters.api.ts
src/api/semesters/index.interface.ts
src/api/words/get-word-ids.api.ts
src/api/words/get-words.api.ts
src/components/atom_tag_button/index.semester.tsx
src/components/atom_word_cards_frame_refresh_button/index.tsx
src/components/molecule_choose_semester/index.tsx
src/components/molecule_tag_button_chunk/index.semesters.tsx
src/components/organism_word_card_frame/index.tsx
src/hooks/semesters/use-apply-semester-details.ts
src/hooks/semesters/use-semesters.hook.ts
src/hooks/words/use-word-ids.hook.ts
src/hooks/words/use-words.hook.ts
src/recoil/words/semesters.state.ts

FE: https://github.com/ajktown/wordnote/pull/32
API: https://github.com/ajktown/api/pull/14

All Semester Tag Removed

---

src/api/auth/get-auth-prep.api.ts
src/components/atom_user_avatar/index.end-user.tsx
src/hooks/auth/use-dev-sign-in-handlers.hook.ts
src/hooks/auth/use-google-sign-in-handlers.hook.ts
src/molecules/StyledAppbar.tsx

FE: https://github.com/ajktown/wordnote/pull/33
API: https://github.com/ajktown/api/pull/15

Profile Picture

---

src/api/words/put-word-by-id.api.ts
src/hooks/words/use-put-word-cache.hook.ts
src/hooks/words/use-put-word.hook.ts

FE: https://github.com/ajktown/wordnote/pull/35
API: https://github.com/ajktown/api/pull/17

Put Word Feature

---

src/api/auth/get-auth-prep.api.ts
src/components/atom_continue_with/index.ms.tsx
src/hooks/use-api-error.hook.ts

FE: https://github.com/ajktown/wordnote/pull/36
API: https://github.com/ajktown/api/pull/18

Automatic User Creation After Sign In

---

src/api/words/get-words.api.ts
src/components/atom_tag_button/index.all_semesters.tsx
src/components/atom_tag_button/index.customized.tsx
src/components/atom_tag_button/index.days_ago.tsx
src/components/atom_tag_button/index.favorite.tsx
src/components/atom_tag_button/index.language.tsx
src/components/atom_tag_button/index.semester.tsx
src/components/atom_word_cards_frame_refresh_button/index.tsx
src/components/atom_word_ids_pagination/index.tsx
src/components/molecule_appbar_search_bar/index.tsx
src/components/molecule_word_card/index.tsx
src/hooks/words/use-reset-search-input.hook.ts
src/hooks/words/use-words.hook.ts
src/recoil/words/words.state.ts

FE: https://github.com/ajktown/wordnote/pull/38
API: https://github.com/ajktown/api/pull/20

No longer gets individual ids

---

scripts/push-to-ecr.sh

FE: https://github.com/ajktown/wordnote/pull/37
API: https://github.com/ajktown/api/pull/19

Scripts for aws deploy

---

src/api/words/post-word.api.ts
src/components/molecule_choose_semester/index.tsx
src/components/organism_word_card_frame/index.tsx
src/hooks/words/use-post-word-from-undo.hook.ts
src/hooks/words/use-post-word.hook.ts

Issue: https://github.com/ajktown/wordnote/issues/47
FE: https://github.com/ajktown/wordnote/pull/48
API: https://github.com/ajktown/api/pull/39

Returns Semester for post word

---

src/hooks/auth/use-google-one-tab-sign-in.hook.ts
src/recoil/app/app.selectors.ts

Issue: https://github.com/ajktown/wordnote/issues/50

Preventing Google SignIn Tab Appearance for Already Signed-In Users

---

.github/PULL_REQUEST_TEMPLATE/general-pr.prt.md
.github/PULL_REQUEST_TEMPLATE/yarn-latest.prt.md

_None_
I would like to use the github template to make consistent PR with great descriptions.
None

pull request template

---

README.md

Docker hub public image

---

README.md

Added pushing command for docker image

doc: modified

---

README.md

_None_
Also wanted to automate `kubectl apply -f k8s`

Very simple doc modified

---

src/hooks/words/use-post-word.hook.ts
src/pages/welcome/index.tsx

_None_
Simple beta warning message before sign in

Beta warning

---

src/components/atom_tag_button/index.semester.tsx
src/components/atom_word_cards_frame_surfing_button/index.tsx
src/hooks/semesters/use-semester-click.hook.ts

surf icon をクリックしたら、latest semester が表示されるようになりました^^

Random Index Selectable with Surfing Icon

---

src/components/atom_word_cards_frame_surfing_button/index.tsx

#72 
https://github.com/ajktown/wordnote/issues/71
Surfing Icon should be visible only when user has 3 or more semesters
If Semesters.length < 3 does not show the surfing icon
Else show the surfing icon
早期returnはまだ適用していません。

Surfing Icon Visible Only When User Has Three Or More Semesters

---

README.md
src/atoms/StyledTextField.tsx
src/components/molecule_new_word_box/index.tsx
src/components/molecule_tag_button_chunk/index.semesters.tsx
src/global.interface.ts
src/hooks/use-dynamic-focus.hook.ts
src/hooks/words/use-post-word-with-string.hook.ts

https://github.com/ajktown/wordnote/issues/70
https://github.com/ajktown/wordnote/issues/49
1. User can post word without keyboard
Posting a new word should not require a mouse

Post Word Card UX Improved

---

.github/pull_request_template.md

https://github.com/ajktown/wordnote/issues/76

fix: template

---

src/components/atom_word_cards_frame_surfing_button/index.tsx

#75 
　　・At least one or more issue is linked to this PR
　　・[The issue template](https://github.com/ajktown/.github/blob/main/issue_template.md) has been replaced to the [issue](https://github.com/ajktown/.github/blob/main/pull_request_template.md#issue) above, if no issue is related to this PR

Hover Message for Surfing Icon

---

src/components/atom_word_cards_frame_surfing_button/index.tsx

Surfing Icon should expand semesters if clicked

---

src/components/atom_word_card_parts/index.example.tsx

https://github.com/ajktown/wordnote/issues/91
- _None_

Example bug fix

---

src/components/molecule_dict_link_button_chunk/index.tsx
src/components/molecule_dict_link_button_chunk/ko-ja-naver.dict-link-button.tsx

Ko-Ja Dictionary for Japanese Natives 

---

src/components/atom_word_card_add_tag_button/index.tsx
src/components/molecule_tag_button_chunk/index.deletable.tsx
src/components/molecule_tag_button_chunk/index.detailed.tsx
src/components/molecule_tag_button_chunk/index.tsx
src/hooks/words/use-post-word-from-undo.hook.ts
src/hooks/words/use-put-word-tag-added.hook.ts
src/hooks/words/use-put-word.hook.ts

Tags should be addable for edit

---

src/components/atom_word_cards_frame_parts/index.refresh-button.tsx

- _None_
- You can directly copy background with issue from the samed/different repository.
- One of the related PRs is linked to the issue under `development`

Refresh Bug

---

README.md

Official Kubernetes repository in GitHub uses `openssf best practices` metrics, and we would like to add the same as well. 
https://github.com/kubernetes/kubernetes

openssf best practices like Kubernetes

---

.github/ISSUE_TEMPLATE/dependency.yaml

https://github.com/ajktown/wordnote/issues/150
- Will be handled in https://github.com/ajktown/wordnote/pull/151

Typo Fixed in Description of the Dependency of issue template

---

src/hooks/words/use-words-with-semesters.hook.ts

The current wordnote loops around semesters if you login in and change semester right away (within 2 seconds)

Hotfix Semester Looping Around

---

src/components/organism_word_card_chunk/index.tsx

https://github.com/ajktown/wordnote/issues/169
```
```

Singular format for one word card

---

src/atoms/StyledIconButton.tsx
src/components/atom_appbar_parts/index.github_icon.tsx
src/molecules/StyledAppbar.tsx

https://github.com/ajktown/wordnote/issues/187

GitHub Icon

---

README.md

https://github.com/ajktown/wordnote/issues/200

Buy me coffee in README.md

---

src/components/molecule_word_card/index.shared.tsx
src/components/organism_shared_word_card_frame/index.tsx
src/pages/share/index.tsx

https://github.com/ajktown/wordnote/issues/165

Shared Word Card Page Visual Improvement

---

src/components/atom_user_avatar/index.end-user.tsx

Buy me coffee please :)
Will consider UI Design later.

First buy me coffee

---

src/components/atom_word_card_parts/index.example-reader.tsx
src/components/molecule_word_card/index.review_mode.tsx
src/components/molecule_word_card/index.share-review.tsx
src/components/molecule_word_card/index.tsx

You can now click the sound button to read your example sentence as the following:
- `TODOs` are filled

Text output app

---

src/components/atom_word_card_parts/index.search-this-word.tsx
src/components/molecule_word_card/index.review_mode.tsx
src/components/molecule_word_card/index.term_search_dialog.tsx
src/components/molecule_word_card/index.tsx
src/components/organism_word_card_frame/index.tsx
src/hooks/words/use-searched-words-by-word-id.hook.ts
src/recoil/words/searchInput.state.ts

Search enabled:
- `TODOs` are filled

Search dialog now supports direct search

---

README.md

There is something called DeepWiki where you can register your repository URL and it will
1. Read your repo
2. Create a wiki page just for the repo
3. Allow you search too with AI powered by `devin AI`
Add the badge:
None
None
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Appropriate ajktown/docs sync pr done if needed
- Review Code
- `Checklist …

Feat: `Ask DeepWiki` Badge

---

package.json

I found it very bothersome to run `yarn latest` & and downgrade certain packages.
Apparently you can use `resolutions` in `package.json` to fix certain versions.
Apply `resolutions` in `package.json`
None
None
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Appropriate ajktown/docs sync pr done if needed
- Review Code
- `Checklist (Right Before PR …

Feat: `resolutions` for `package.json`
