ajktown/wordnote

- package.json
- yarn.lock
_None_
Next js server has recommended to install `sharp` for production mode.
> yarn: add sharp

- src/api/words/interfaces/index.ts
- src/api/words/post-word.api.ts
- src/components/atom_tag_button/index.semester.tsx
- src/hooks/words/use-post-word-with-string.hook.ts
- src/hooks/words/use-post-word.hook.ts
- src/lambdas/parse-input-into-word.lambda.ts
_None_
When you click a semester, your search queries like selected languages, tags, and others must be deselected.
> Semester click reset queries

- src/atoms/StyledTextButton.tsx
- src/components/atom_word_card_delete_button/index.tsx
- src/components/atom_word_card_undo_delete_button/index.tsx
- src/hooks/words/use-delete-word-cache.hook.ts
- src/hooks/words/use-delete-word.hook.ts
- src/hooks/words/use-post-word-from-undo.hook.ts
When a user wants to delete his/her own word, it has no loading design so it is a bit confusing
- Trashcan
- Undo
- Hide
> Loading icons For Delete

- src/api/words/interfaces/index.ts
- src/components/atom_word_card_confirm_modify_button/index.tsx
- src/components/atom_word_card_parts/index.example.tsx
- src/components/molecule_word_card/index.editing_mode.tsx
- src/components/molecule_word_card/index.tsx
- src/components/molecule_word_card_editing_text_field/index.tsx
- src/hooks/words/use-put-word-cache.hook.ts
- src/lambdas/parse-input-into-word.lambda.ts
When you study word, you want to know where you get the words. Wordnote now supports link for example sentence to make yourself remember your words even more.
- https://github.com/ajktown/docs/pull/21
- https://github.com/ajktown/api/pull/56
- https://github.com/ajktown/wordnote/pull/87
> Link for Example

- src/components/atom_tag_button/index.all_semesters.tsx
- src/components/atom_tag_button/index.customized.tsx
- src/components/atom_tag_button/index.days_ago.tsx
- src/components/atom_tag_button/index.favorite.tsx
- src/components/atom_tag_button/index.language.tsx
- src/components/atom_tag_button/index.semester.tsx
- src/components/atom_word_cards_frame_surfing_button/index.tsx
- src/components/molecule_choose_semester/index.tsx
- src/components/molecule_tag_button_chunk/index.detailed.tsx
- src/components/organism_word_card_chunk/index.no_words_found.tsx
- src/hooks/words/use-put-word-favorite.hook.ts
- src/recoil/app/app.selectors.ts
- src/recoil/words/words.selectors.ts
The previous name for `tags.selector.ts` contains the derived selector state of `words.state.ts` 
- _None_
> Appropriate file name for selector

- src/components/atom_word_card_parts/index.example.tsx
> Double Quote Bug for empty sample example

- src/components/atom_word_card_parts/index.example.tsx
Font for example varies depending on the following condition of example
- Both `example` and `exampleLink` is present
- `example` is present but `exampleLink` is not
- `example` is not present but `exampleLink` is
- Both `example` and `exampleLink` is not present
- _None_
> Same Variant for Example & ExampleLink

- src/recoil/preferences/preference.state.ts
I should add dummy data for preference so that @akanex115  can develop a bit easier.
> Dummy data for preference state

- src/pages/welcome/index.tsx
We want to let the developers sign in right away with dev token under development env.
- _None_
> Dev Token in Welcome Page

- src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
- src/hooks/preference/use-preference.hook.ts
- src/hooks/words/use-words-with-semesters.hook.ts
There was a bug in refresh defined in issue https://github.com/ajktown/wordnote/issues/117 and was handled in the pr https://github.com/ajktown/wordnote/pull/119.
The pr however has decreased the performance due to the lack of simultaneous request to the API.
- Make sure the simultaneous run is well documented in the activity diagram
- Create an issue that handles this in https://github.com/ajktown/docs/issues/36
- _None_
- You can directly copy background with issue from the samed/different repository.
- One of the related PRs is linked to the issue under `development`
> On Click Refresh Performance

- src/components/atom_tag_button/index.days_ago.tsx
https://github.com/ajktown/wordnote/issues/131
- _None_
> Days Ago Unselects Favorite

- src/components/atom_word_card_parts/index.example.tsx
- src/components/atom_word_cards_frame_parts/index.review-mode.tsx
- src/components/molecule_word_card/index.review_mode.tsx
- src/components/molecule_word_card/index.tsx
- src/components/organism_word_card_frame/index.tsx
- src/hooks/words/use-put-word-tag-added.hook.ts
- src/recoil/preferences/preference.state.ts
By clicking the red button, you can review your Wordcard orange
as
> Review mode with meaning only

- src/atoms/StyledVisibility.tsx
- src/components/atom_word_cards_frame_parts/index.review-mode.tsx
- src/components/molecule_word_card/index.review_mode.tsx
Review mode was introduced in #142 but has found out that peek mode would be great to review even faster as following:
> Review mode peek feature

- src/hooks/words/use-words-with-semesters.hook.ts
Latest semester is not selected when you sign in, as the red below:
> Refresh Button Bug with Latest Semester Not Automatically Selected

- src/components/atom_top_of_page_button/index.tsx
- src/components/organism_word_card_chunk/index.tsx
It is bothersome to go to the top of the page at the bottom of Wordcard frame, if you have many words.
- ![Screenshot 2024-01-01 at 10 04 45](https://github.com/ajktown/wordnote/assets/53258958/7d5c972d-e623-4261-b980-bbd7f4003b2e)
> Top of Page Button

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/dependency.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/enhancement.yaml
- .github/ISSUE_TEMPLATE/infrastructure.yaml
- .github/ISSUE_TEMPLATE/performance.yaml
- .github/ISSUE_TEMPLATE/refactor.yaml
Kubernetes like issue templates for AJK Town.
https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE
> Kubernetes like issue for wordnote fe

- src/components/molecule_word_card/index.review_mode.tsx
You can edit word during the review
> Edit Word during Review Mode

- src/atoms/StyledIconButton.tsx
https://github.com/ajktown/wordnote/issues/110
> Question Mark for Disabled Icons with Hover Message

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/dependency.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/enhancement.yaml
- .github/ISSUE_TEMPLATE/infrastructure.yaml
- .github/ISSUE_TEMPLATE/performance.yaml
- .github/ISSUE_TEMPLATE/refactor.yaml
As I've introduced the issue template in the PR https://github.com/ajktown/wordnote/pull/149,
I first thought it would be better to have "why we need this", but for the current AJK Town projects, I don't think we need to explain why we need it at this point.
Also instead of having a question for background, I think writing "Background" and its sub description would be cleaner to read & matches with the PRs template (which I love)
> Customize issue template to the ajktown wordnote based on k8s

- src/components/molecule_word_card/index.tsx
(https://github.com/ajktown/wordnote/issues/154)
```
const onClickWordCard = useRecoilCallback(({ set }) => () => {
console.log("HIHIHI")
!editingMode && set(selectedWordIdForDialogState, wordId)
}, [wordId, editingMode])
```
> Fix function name with on~ prefix

- src/components/organism_word_card_chunk/index.tsx
- src/components/organism_word_card_frame/index.tsx
(https://github.com/ajktown/wordnote/issues/134)
> Wordnote Frame with WordCards Count

- src/hooks/app/use-on-sign-out-app.hook.ts
The current logic of the sign out flow won't reset state, if the api server does not respond properly
> Try Catch for Sign Out Flow

- src/hooks/app/use-is-app-booted.hook.ts
- src/hooks/use-handle-api-error.hook.ts
issue https://github.com/ajktown/wordnote/issues/44
We refactored the function names in the PR(https://github.com/ajktown/wordnote/pull/158), but there were components that were not changed.
```
```
> refactor onSignOutApp function name

- src/components/atom_word_card_add_tag_button/index.tsx
- src/components/atom_word_card_favorite_icon/index.tsx
- src/components/molecule_new_word_box/index.tsx
- src/components/organism_word_card_chunk/index.search_not_found.tsx
- src/hooks/preference/use-put-preference-native-language.hook.ts
- src/hooks/use-dynamic-focus.hook.ts
- src/hooks/words/use-post-word-with-string.hook.ts
issue https://github.com/ajktown/wordnote/issues/44
We refactored the function names in the PRs(https://github.com/ajktown/wordnote/pull/158 & https://github.com/ajktown/wordnote/pull/163), but there were components that were not changed.
```
```
> refactor names of functionaries

- src/components/molecule_word_card/index.review_mode.tsx
Current action buttons during the review mode is limited and a bit inconvenient.
- Problem: Review Mode & Non Peek Mode
- No dictionary
- Unnecessary editing icon that is different from normal mode
- Problem: Review Mode & Peek Mode
- Not enough action buttons that 
- Unnecessary editing icon that is different from normal mode
> Review Mode with More Action Buttons

- src/api/words/interfaces/index.ts
- src/components/molecule_word_card/index.shared.tsx
- src/pages/share/index.tsx
https://github.com/ajktown/wordnote/issues/164
```
```
> Showing Customized Tag on Shared Word Card

- src/components/atom_word_card_parts/index.example.tsx
During the review mode, only by looking at the meaning of term is not enough to test yourself.
normal mode:
yes double quote in red, and no double quote in orange
review mode:
Shows the example sentence in red, but not in orange (due to insufficient information)
> Underscore during the review mode

- src/components/atom_tag_chip/index.semester-code.tsx
- src/components/molecule_tag_button_chunk/index.tsx
- src/hooks/words/use-words.hook.ts
The current Wordnote search is scoped within the selected semester.
This is extremely inconvenient, as users sometimes want to see if they have ever added words.
> SearchInput searches is non-semester scoped

- src/components/atom_word_card_parts/index.search-this-word.tsx
- src/components/molecule_word_card/index.tsx
Search feature in Wordnote has been drastically improved in https://github.com/ajktown/wordnote/pull/179.
Now users want to search certain word right away without typing.
> Search this word button

- src/api/action-groups/get-action-groups.api.ts
- src/components/atom_appbar_parts/index.to_consistency_page_button.tsx
- src/components/atom_word_cards_frame_parts/index.refresh-button.tsx
- src/hooks/action-groups/use-action-groups.hook.ts
- src/hooks/words/use-delete-word.hook.ts
- src/hooks/words/use-post-word-from-undo.hook.ts
- src/hooks/words/use-post-word.hook.ts
- src/lambdas/axios-request-success.lambda.ts
- src/lambdas/get-env.lambda.ts
- src/molecules/StyledAppbar.tsx
- src/recoil/action-groups/action-groups.state.ts
Consistency GPT app is (will be) launched and Wordnote should suggest users of Wordnote to go check out!
Sample:
- onPostWords
- onDeleteWords
- onPostWordsFromUndo
> Consistency Page is now open in beta. Wordnote should suggest users to go

- src/components/atom_word_card_parts/index.example.tsx
It is actually confusing to show `???` when double quotes are not given during the review mode.
> No longer shows the ??? during review mode without double quotes

- src/components/organism_word_card_chunk/index.search_not_found.tsx
- src/hooks/words/use-post-word-with-string.hook.ts
- src/hooks/words/use-post-word.hook.ts
https://github.com/ajktown/wordnote/issues/190
> Refactor usePostWord with returned value isLoading

- src/atoms/StyledIconButtonNewPage.tsx
- src/components/atom_shared_word_card_parts/index.add-word-button.tsx
- src/hooks/app/use-is-app-booted.hook.ts
- src/pages/share/index.tsx
Implement a button for the shared page to add a certain word right away
If Not Signed in:
If Signed in:
If signed in and already added:
> Shared Word Page now let users to download the word if signed in

- src/components/atom_word_card_parts/index.search-this-word.tsx
- src/components/molecule_tag_button_chunk/index.tsx
- src/components/molecule_word_card/index.review_mode.tsx
- src/components/molecule_word_card/index.search_dialog.tsx
- src/components/molecule_word_card/index.share-review.tsx
- src/components/molecule_word_card/index.tsx
- src/components/organism_word_card_frame/index.tsx
- src/hooks/words/use-searched-words-by-word-id.hook.ts
- src/recoil/words/searchInput.state.ts
Search button in the WordCard now will open a dialog instead with the search results.
You can also see the full results if you want to edit it. (Ideally it is great to be able to modify too, but decide not to)
> Search dialog openable in WordCard

- src/hooks/use-key-press.hook.ts
https://github.com/ajktown/wordnote/issues/188
> EnterKey bug on conversion

- src/components/molecule_dict_link_button_chunk/index.tsx
- src/components/molecule_tag_button_chunk/index.tsx
- src/components/molecule_word_card/index.review_mode.tsx
- src/components/molecule_word_card/index.tsx
- src/styles/Home.module.css
https://github.com/ajktown/wordnote/issues/166
> Dictionary icons not visible when window width not big enough (smartphone screens)

- README.md
README.md is introduced for each directory under the dev_wordnote in https://github.com/ajktown/docs/pull/87/files
Make sure that main README.md of Wordnote repository directs the dev doc in ajktown/docs
> Introduce dev_wordnote for developers of Wordnote

- src/components/atom_word_card_confirm_modify_button/index.tsx
- src/components/molecule_new_word_box/index.tsx
- src/global.interface.ts
- src/hooks/use-key-press.hook.ts
https://github.com/ajktown/wordnote/issues/202
> Implement `command + enter` for apply modification

- README.md
- src/components/atom_tag_chip/index.every-favorite.tsx
- src/components/atom_word_ids_pagination/index.tsx
- src/components/molecule_tag_button_chunk/index.semesters.tsx
- src/components/organism_word_card_chunk/index.no_words_found.tsx
- src/hooks/semesters/use-semester-click.hook.ts
- src/hooks/words/use-words-by-favorite.hook.ts
- src/recoil/words/semesters.state.ts
- src/recoil/words/words.selectors.ts
You can now select favorite words from every semester you have:
> Favorite Icon forEvery Semester

- src/components/atom_word_card_add_tag_button/index.tsx
- src/components/atom_word_card_confirm_modify_button/index.tsx
- src/components/molecule_new_word_box/index.tsx
Implemented `command + enter` for apply modification in the word card dialog. (Handled in https://github.com/ajktown/wordnote/pull/210)
I think it would be useful to implement `command + enter` for apply when creating a new tag.
> Implement 'command + enter' for apply new tag

- src/api/words/interfaces/index.ts
- src/components/atom_shared_word_card_parts/index.add-word-button.tsx
- src/components/atom_word_card_confirm_modify_button/index.tsx
- src/components/atom_word_card_parts/index.definition.tsx
- src/components/atom_word_card_parts/index.term-and-pronunciation.tsx
- src/components/molecule_word_card/index.editing_mode.tsx
- src/components/molecule_word_card/index.review_mode.tsx
- src/components/molecule_word_card/index.search_dialog.tsx
- src/components/molecule_word_card/index.share-review.tsx
- src/components/molecule_word_card/index.shared.tsx
- src/components/molecule_word_card/index.tsx
- src/hooks/words/use-put-word-cache.hook.ts
- src/lambdas/parse-input-into-word.lambda.ts
You can edit sub definition on FE too after the API implementation: https://github.com/ajktown/api/pull/122
If you go ReviewMode, your sub definition won't be visible, and you can utilize this not to show hints during the review.
Editing:
Visual:
- `TODOs` are filled
> Sub defintion editable

- src/api/preferences/patch-preference.api.ts
- src/api/words/patch-word-by-id.api.ts
- src/components/atom_preference_language_checkbox/index.tsx
- src/components/molecule_gpt_key_registerer/index.tsx
- src/hooks/preference/use-patch-preference-native-language.hook.ts
- src/hooks/preference/use-patch-preference.hook.ts
- src/hooks/words/use-put-word-cache.hook.ts
- src/hooks/words/use-put-word.hook.ts
Use patch instead, as the `PUT` apis will be deprecated in the following issue: https://github.com/ajktown/api/issues/131
- `TODOs` are filled
> Use patch instead

- .github/workflows/docker-image.yaml
- README.md
Locally pushing image every time you make a release is tedious.
> GitHub Action for Automatic Docker Registry Push

- .github/workflows/docker-image.yaml
The current pipeline builds an image on x86, and therefore should disable it temporarily.
> Disable Docker Build for latest

- src/components/molecule_word_card/index.review_mode.tsx
- src/global.constants.ts
Show the country code (based on language) to review easier:
- N/A
- Mobile View Operation Check is done
- `What's done` is filled & matches to the actual changes
- Review Code
- Check if issue under `Development` is fully handled if exists
> Feat: Wordcard in Review Mode shows country flag to review easier

- src/components/atom_word_cards_frame_parts/index.fixed-tags-button.tsx
- src/components/dialog_fixed_tags/index.tsx
- src/components/molecule_new_word_box/index.tsx
- src/components/molecule_tag_button_chunk/index.fixed.tsx
- src/components/organism_word_card_frame/index.tsx
- src/hooks/words/use-post-word-with-string.hook.ts
- src/recoil/index.keys.ts
- src/recoil/words/words.state.ts
Sometimes, I need to add multiple words with the same tags within a short period.
Currently, each word and tag must be added individually, which increases the risk of:
- typos
- omissions
- or other mistakes
- N/A
- Mobile View Operation Check is done
- `What's done` is filled & matches to the actual changes
- Review Code
- Check if issue under `Development` is fully …
> Feat: `Fixed Tags`

- src/api/words/interfaces/index.search-params.ts
- src/api/words/interfaces/index.ts
- src/atoms/StyledIconButtonPin.tsx
- src/components/atom_shared_word_card_parts/index.add-word-button.tsx
- src/components/atom_word_card_favorite_icon/index.tsx
- src/components/atom_word_card_parts/index.pin-button.tsx
- src/components/molecule_word_card/index.review_mode.tsx
- src/components/molecule_word_card/index.tsx
- src/hooks/words/use-put-word-is-pinned.hook.ts
- src/lambdas/parse-input-into-word.lambda.ts
- src/recoil/words/words.selectors.ts
*The same Background as the following PR: https://github.com/ajktown/api/pull/159*
Pin the word to make it listed on the top of the list all the time:
- Depends on the following API PR: https://github.com/ajktown/api/pull/159
- Mobile View Operation Check is done
- `What's done` is filled & matches to the actual changes
- Review Code
- Check if issue under `Development` …
> Feat: `PinButton` for WordCard

- src/hooks/use-key-press.hook.ts
https://github.com/ajktown/wordnote/issues/241
Bug fixed.
- N/A
- Mobile View Operation Check is done
- `What's done` is filled & matches to the actual changes
- Review Code
- Check if issue under `Development` is fully handled if exists
> Bugfix: Cannot Re-Modify Word After Using `Command` + `Enter` 

- src/components/atom_word_card_parts/index.definition.tsx
- src/components/molecule_word_card/index.review_mode.tsx
I found myself not catching the flag during the review mode.
Into
None
None
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Appropriate ajktown/docs sync pr done if needed
- Review Code
- Check if issue …
> Fix: Review Mode Word Card Language Flag Position

- package.json
- src/components/atom_word_card_parts/index.share-button.tsx
- src/components/dialog_shared_resource/index.tsx
- src/recoil/shared-resource/shared-resource.state.ts
- yarn.lock
React Recoil has not been maintained for long time after the massive layoff around 2023
I would like to import the package manager `jotai` replacing the Recoil
None
Gradually replace other Recoil stuff 
- `What's done?` is filled
- `What are the related PRs?` is filled
- `What's next?` is filled
- Mobile View Operation Check is done, if frontend related
- Double-check `What's done?` matches to the actual changes
- Appropriate ajktown/docs sync pr done if needed
- Review Code
- `Checklist (Right Before PR Review …
> Feat: `jotai` as a sample, replacing Recoil React
